version: "3.9"

services:
  tm-db:
    image: postgres:14.2
    container_name: ${POSTGRES_HOST}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./:/app
      - ./postgres.conf:/etc/postgresql/postgresql.conf
  tm-django:
    container_name: tm-django
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - tm-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_ENV=${DJANGO_ENV}