version: "3.9"

services:
  tm-db:
    image: postgres:14.2
    container_name: ${POSTGRES_HOST}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5433"
    volumes:
      - ./:/app
      - ./postgres.conf:/etc/postgresql/postgresql.conf
  tm-django:
    container_name: tm-django
    build: .
    command: gunicorn --bind 0.0.0.0:7078 main.wsgi
    volumes:
      - ./:/app
    ports:
      - "8000:7078"
    depends_on:
      - tm-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}